name: nebula
description: A command-line utility to extract Stellarium DSO Catalog into JSON.
version: 0.1.0

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  raw: ^0.2.0
  equatable: ^1.2.0
  args: ^1.6.0
  restio: ^0.10.8

dev_dependencies:
  test: ^1.15.0
  pedantic: ^1.9.0

executables:
  nebula:
